export const AUTH_LOGIN_START = "AUTH_LOGIN_START";

export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const AUTH_SIGNUP_START = "AUTH_SIGNUP_START";

export const AUTH_SIGNUP_FINISH = "AUTH_SIGNUP_FINISH";

export const AUTH_VALIDATION_SUCCESSFUL = "AUTH_VALIDATION_SUCCESSFUL";

export const AUTH_VALIDATION_FAIL = "AUTH_VALIDATION_FAIL";

export const AUTH_LOGIN_SUCCESSFUL = "AUTH_LOGIN_SUCCESSFUL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const IDEA_SHARE_SUCCESSFUL = "IDEA_SHARE_FINISH";

export const IDEA_SHARE_NEUTRAL = "IDEA_SHARE_NEUTRAL";

export const IDEA_OWN = "IDEA_OWN";

export const IDEA_NEW = "IDEA_NEW";

export const IDEA_GET_THE = "IDEA_GET_THE";

export const IDEA_GET_ACTIONS = "IDEA_GET_ACTIONS";

export const IDEA_LIKE = "IDEA_LIKE";

export const IDEA_DISLIKE = "IDEA_DISLIKE";

export const IDEA_SAVE = "IDEA_SAVE";

export const IDEA_NOT_LIKE = "IDEA_NOT_LIKE";

export const IDEA_NOT_DISLIKE = "IDEA_NOT_DISLIKE";

export const IDEA_COMMENT_ADD = "IDEA_COMMENT_ADD";

export const IDEA_COMMENT_GET = "IDEA_COMMENT_GET";

export const IDEA_GET_SAVED = "IDEA_GET_SAVED";

export const IDEA_GET_LIKED = "IDEA_GET_LIKED";

export const POPULAR_GET_TOPICS = "POPULAR_GET_TOPICS";

export const POPULAR_GET_USERS = "POPULAR_GET_USERS";

export const PROFILE_GET = "PROFILE_GET";

export const SEARCH_START = "SEARCH_START";

export const SEARCH_FINISH = "SEARCH_FINISH";

export const SEARCH_RESET = "SEARCH_RESET";

export const SEARCH_GOT_RESPONSE = "SEARCH_GOT_RESPONSE";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";

export const TRUE_NOTIFIED = "TRUE_NOTIFIED";

export const NOT_NOTIFIED = "NOT_NOTIFIED";

export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";

export const AUTH_LOGINLOADING_FALSE = "AUTH_LOGINLOADING_FALSE";

export const IDEA_LOADING = "IDEA_LOADING";
